### ISSUE TITLE
BlockDataConsumer endpoint to track world state in Haskell

### ISSUE THREAD

**Issue by kevin-li-195** [djeik/libt#8]
When turtles move, they will perform 3 inspections of adjacent blocks (top, front, and bottom) and send the block position along with the block data (block data is in the form "modname:blockname") to the blockdata endpoint. We need to implement the blockdata endpoint in Servant so that we can track the world status (using Postgres).

**Comment by tsani** [comment]
Should go on [atuin-server](https://github.com/labcoders/atuin-server).
